<!--
 * @Author: your name
 * @Date: 2021-05-29 08:04:01
 * @LastEditTime: 2021-05-29 09:00:46
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /01-good/use/05. python/016.异常处理.md
-->

> ## 异常处理

#

### 1. Python 标准异常总结

```py
AssertionError	        #断言语句（assert）失败
AttributeError	        #尝试访问未知的对象属性
EOFError	            #用户输入文件末尾标志EOF（Ctrl+d）
FloatingPointError	    #浮点计算错误
GeneratorExit	        #generator.close()方法被调用的时候
ImportError	            #导入模块失败的时候
IndexError	            #索引超出序列的范围
KeyError	            #字典中查找一个不存在的关键字
KeyboardInterrupt	    #用户输入中断键（Ctrl+c）
MemoryError	            #内存溢出（可通过删除对象释放内存）
NameError	            #尝试访问一个不存在的变量
NotImplementedError	    #尚未实现的方法
OSError	                #操作系统产生的异常（例如打开一个不存在的文件）
OverflowError	        #数值运算超出最大限制
ReferenceError	        #弱引用（weak reference）试图访问一个已经被垃圾回收机制回收了的对象
RuntimeError	        #一般的运行时错误
StopIteration	        #迭代器没有更多的值
SyntaxError	            #Python的语法错误
IndentationError	    #缩进错误
TabError	            #Tab和空格混合使用
SystemError	            #Python编译器系统错误
SystemExit	            #Python编译器进程被关闭
TypeError	            #不同类型间的无效操作
UnboundLocalError	    #访问一个未初始化的本地变量（NameError的子类）
UnicodeError	        #Unicode相关的错误（ValueError的子类）
UnicodeEncodeError	    #Unicode编码时的错误（UnicodeError的子类）
UnicodeDecodeError	    #Unicode解码时的错误（UnicodeError的子类）
UnicodeTranslateError	#Unicode转换时的错误（UnicodeError的子类）
ValueError	            #传入无效的参数
ZeroDivisionError	    #除数为零

```

### 2.Python 内置异常类的层次结构

```py
BaseException
+-- SystemExit
+-- KeyboardInterrupt
+-- GeneratorExit
+-- Exception
      +-- StopIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning

```

### 3.try-except 语句

```py
    #语法
    #检测try内容的代码,处理制定的异常,进行友好输出.
try:
    检测范围
except Exception[as reasion]:
    出现异常后的处理代码.

```

```py
   #案例
    #异常处理:OSError
try:
    f = open('我为什么是一个文件.txt')
    print(f.read())
except OSError as error:
    print('操作文件出错了,原因是:',error)

#输出: 操作文件出错了,原因是: [Errno 2] No such file or directory: '我为什么是一个文件.txt'


```

### 4.try-finally 语句

```py
    #语法
    #检查try内容的代码,无论如何finally的代码都会执行。
try:
    检查范围
except Exception [as reason]:
    出现异常[Exception]后的处理代码
finally:
    无论如何都会被执行的代码.

```

```py
    #案例
try:
    f = open('我为什么是一个文件.txt','w')
    print(f.write('我存在了'))
    sum=1+'1'                       #<-----这里特意做了一个会产生异常的代码
except (OSError,TypeError) as error:
    print('操作文件出错了,原因是:',error)
finally:                            #<----处理异常后,继续会执行的代码部分
    f.close()

```

### 5.raise 自定义崩溃输出

```py
    #语法
    #直白讲就是:自己定义python崩溃报错时的输出内容.
    raise [exceptionName [(reason)]]
    raise [python已有的崩溃异常名] (定义输出内容)


```

```py
#案例
>>> raise ZeroDivisionError('除数为零的异常')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: 除数为零的异常               <------自定义崩溃的时候输出什么了。


 #案例
try:
    a = input("输入一个数：")
    #判断用户输入的是否为数字
    if(not a.isdigit()):
        raise ValueError("a 必须是数字")
except ValueError as e:
    print("引发异常：",repr(e))

#输入一个数：a
#引发异常： ValueError('a 必须是数字',)
```
